import {
  ShieldAlert,
  ScrollText,
  FileText,
  Wrench,
  NotebookPen,
  GitCompareArrows,
  HelpCircle,
  CheckCircle2,
  Sparkles,
  FileWarning,
  Gavel,
  Gauge,
} from "lucide-react";
import type { ChatTurnKind, CopilotAnswerResponse } from "../types";

const KIND_CONFIG: Record<ChatTurnKind, { icon: typeof HelpCircle; label: string; accent: string }> = {
  ask: { icon: HelpCircle, label: "Answer", accent: "text-info" },
  explainRule: { icon: ScrollText, label: "Rule Explained", accent: "text-accent" },
  explainViolations: { icon: FileWarning, label: "Violations Explained", accent: "text-critical" },
  summarize: { icon: FileText, label: "Inspection Summary", accent: "text-ai-blue" },
  recommend: { icon: Wrench, label: "Manufacturer Guidance", accent: "text-warning" },
  notes: { icon: NotebookPen, label: "Officer Notes", accent: "text-success" },
  compare: { icon: GitCompareArrows, label: "Comparison", accent: "text-ai-violet" },
  notice: { icon: Gavel, label: "Compliance Notice", accent: "text-ai-violet" },
  risk: { icon: Gauge, label: "Risk Analysis", accent: "text-warning" },
};

/** A line is treated as a bullet if it starts with a markdown-ish list marker — Gemini/Claude answers commonly use these when asked for structured output (recommendations, comparisons, summaries). */
function parseLines(text: string): { type: "bullet" | "text"; content: string }[] {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => {
      const bulletMatch = line.match(/^(?:[-*•]|\d+[.)])\s+(.*)/);
      return bulletMatch ? { type: "bullet" as const, content: bulletMatch[1] } : { type: "text" as const, content: line };
    });
}

export function AnswerCard({ kind, answer }: { kind: ChatTurnKind; answer: CopilotAnswerResponse }) {
  const config = KIND_CONFIG[kind];
  const Icon = config.icon;
  const lines = parseLines(answer.answer);
  const hasBullets = lines.some((l) => l.type === "bullet");

  return (
    <div className="mr-6 space-y-2.5 rounded-xl border border-border bg-surface-raised p-3.5 shadow-xs">
      <div className="flex items-center gap-1.5">
        <Icon className={`size-3.5 ${config.accent}`} />
        <p className="text-xs font-semibold text-foreground">{config.label}</p>
      </div>

      {hasBullets ? (
        <ul className="space-y-1.5">
          {lines.map((line, i) =>
            line.type === "bullet" ? (
              <li key={i} className="flex items-start gap-2 text-sm text-foreground-secondary">
                <CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-success" />
                <span>{line.content}</span>
              </li>
            ) : (
              <p key={i} className="text-sm text-foreground">{line.content}</p>
            ),
          )}
        </ul>
      ) : (
        <p className="whitespace-pre-wrap text-sm text-foreground">{answer.answer}</p>
      )}

      <div className="flex items-center gap-1 border-t border-border pt-2 text-[10px] text-faint-foreground">
        {answer.generatedByAi ? (
          <>
            <Sparkles className="size-2.5" /> Generated by {answer.provider}
          </>
        ) : (
          <>
            <ShieldAlert className="size-2.5" /> Deterministic answer — not AI-generated
          </>
        )}
      </div>
    </div>
  );
}
